home:
    path: /
    controller: App\Controller\HomeController::index
properties:
    path: /biens 
    controller: App\Controller\PropertyController::index
property:
    path: /bien/{slug}/{id}
    controller: App\Controller\PropertyController::show
    requirements:
        page: '[a-z0-9\-]*'
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
