home:
    path: /
    controller: App\Controller\HomeController::index
properties:
    path: /biens 
    controller: App\Controller\PropertyController::index
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
